---
- name: ensure vitess group
  become: yes
  become_user: root
  group:
    name: '{{ vitess_group }}'
    state: present

- name: ensure vitess user
  become: yes
  become_user: root
  user:
    name: '{{ vitess_user }}'
    group: '{{ vitess_group }}'
    state: present

- name: ensure vitess directories
  become: yes
  become_user: root
  with_items:
    - '{{ vitess_root }}'
    - '{{ vitess_root }}/socket'
  file:
    state: directory
    path:   '{{ item }}'
    owner:  '{{ vitess_user }}'
    group:  '{{ vitess_group }}'
    mode: 0755

- name: ensure config directories
  become: yes
  become_user: root
  with_items:
    - /etc/vitess/conf
  file:
    state: directory
    path: '{{ item }}'
    owner: '{{ vitess_user }}'
    group: '{{ vitess_group }}'
    mode: 0644

- name: install systemd units
  become: yes
  become_user: root
  register: vttablet_service_modified
  with_items:
    - s: vttablet@.service
      d: /etc/systemd/system/vttablet@.service
    - s: mysqlctld@.service
      d: /etc/systemd/system/mysqlctld@.service
    - s: mysqld_exporter@.service
      d: /etc/systemd/system/mysqld_exporter@.service
  template:
    src: '{{ item.s }}.j2'
    dest: '{{ item.d }}'
    owner: '{{ vitess_user }}'
    group: '{{ vitess_group }}'
    mode: '0644'

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: vttablet_service_modified is changed
  systemd:
    daemon_reload: yes

- name: install config files
  include_tasks: vttablet.yml
  loop: '{{ tablets }}'
  loop_control:
    loop_var: tablet
