---
- import_playbook: provision.yml
  when: provision is defined
- import_playbook: update.yml
  when: update is defined
- import_playbook: configure.yml
- import_playbook: oltp_read_write.yml
  when: tpcc is not defined
- import_playbook: tpcc.yml
  when: tpcc is defined
