---
all:
  vars:
    vitess_git_version: "HEAD"
    cell: local
    keyspace: main
  hosts:
    127.0.0.1:
  children:
    sysbench:
      hosts:
        127.0.0.1:
    prometheus:
      hosts:
        127.0.0.1:
    etcd:
      hosts:
        127.0.0.1:
    vtctld:
      hosts:
        127.0.0.1:
    vtgate:
      vars:
        vtgate_query_cache_size: 1000
        vtgate_max_goproc: 6
      hosts:
        127.0.0.1:
          gateways:
            - id: 1
              port: 15001
              mysql_port: 13306
              grpc_port: 15306
            - id: 2
              port: 15002
              mysql_port: 13307
              grpc_port: 15307
            - id: 3
              port: 15003
              mysql_port: 13308
              grpc_port: 15308
            - id: 4
              port: 15004
              mysql_port: 13309
              grpc_port: 15309
            - id: 5
              port: 15005
              mysql_port: 13310
              grpc_port: 15310
            - id: 6
              port: 15006
              mysql_port: 13311
              grpc_port: 15311
    vttablet:
      vars:
        vitess_memory_ratio: 0.6
        vttablet_query_cache_size: 10000
        vttablet_max_goproc: 24
      hosts:
        127.0.0.1:
          tablets:
            - id: 1001
              keyspace: main
              shard: -80
              pool_size: 500
              transaction_cap: 2000
              port: 16001
              grpc_port: 17001
              mysql_port: 18001
              mysqld_exporter_port: 9104
            - id: 2001
              keyspace: main
              shard: 80-
              pool_size: 500
              transaction_cap: 2000
              port: 16002
              grpc_port: 17002
              mysql_port: 18002
              mysqld_exporter_port: 9105
