---
- hosts: all
  roles:
    - host
    - cloudalchemy.node-exporter
    - vitess-build
  tasks:

- hosts: etcd
  roles:
    - etcd
- hosts: vtctld
  roles:
    - vtctld
- hosts: vtgate
  roles:
    - vtgate
- hosts: vttablet
  roles:
    - vttablet
  tags:
    - configuration

- hosts: sysbench
  become: yes
  become_user: root
  roles:
    - sysbench
  vars:
    gateways: "{% set targets = [] -%}{% for host in groups['vtgate'] -%}{% for gateway in hostvars[host]['gateways'] -%}{{targets.append( hostvars[host]['ansible_default_ipv4']['address']+':'+ (gateway.mysql_port | default(13306) |
string ))}}{% endfor -%}{% endfor -%}{{ targets }}"
  tasks:
    - name: Install iptables
      package:
        name: 'iptables'
        state: present
        update_cache: true
    - name: Set up Masquerading
      shell: |
        iptables -t nat -A POSTROUTING -j MASQUERADE
        sysctl -w net.ipv4.conf.lo.route_localnet=1
    - name: Flush all rules
      shell: |
        iptables -t nat -F OUTPUT
    - name: Set up VTGate Loadbalancing
      shell: |
        iptables -t nat -A OUTPUT -p tcp --dport 3306 -m state --state NEW -m statistic --mode nth --every {{ ((gateways | length) - index) }} --packet 0 -j DNAT --to-destination {{ gateway }}
      with_items: '{{ gateways }}'
      loop_control:
        loop_var: gateway
        index_var: index
  tags:
    - test

- hosts: prometheus
  become: yes
  become_user: root
  tags:
    - prometheus
  roles:
    - cloudalchemy.prometheus
  vars:
    vitess_cluster: 'main'
    tablet_targets: "{% set targets = [] -%}{% for host in groups['vttablet'] -%}{% for tablet in hostvars[host]['tablets'] -%}{{targets.append( hostvars[host]['ansible_default_ipv4']['address']+':'+ (tablet.port | default(16001) | string ))}}{% endfor -%}{% endfor -%}{{ targets }}"
    mysqld_targets: "{% set targets = [] -%}{% for host in groups['vttablet'] -%}{% for tablet in hostvars[host]['tablets'] -%}{{targets.append( hostvars[host]['ansible_default_ipv4']['address']+':'+ (tablet.mysqld_exporter_port | default(9104) |string ))}}{% endfor -%}{% endfor -%}{{ targets }}"
    gateway_targets: "{% set targets = [] -%}{% for host in groups['vtgate'] -%}{% for gateway in hostvars[host]['gateways'] -%}{{targets.append( hostvars[host]['ansible_default_ipv4']['address']+':'+ (gateway.port | default(15001) | string ))}}{% endfor -%}{% endfor -%}{{ targets }}"
    vtctld_targets: "{% set targets = [] -%}{% for host in groups['vtctld'] -%}{{targets.append( hostvars[host]['ansible_default_ipv4']['address']+':'+ (vtctld_port | default(15000) | string ))}}{% endfor -%}{{ targets }}"
    node_targets: "{% set targets= [] -%}{% for host in groups['all'] -%}{{targets.append( hostvars[host]['ansible_default_ipv4']['address']+':9100' )}}{% endfor -%}{{ targets }}"
    prometheus_targets:
      tablets:
      - targets: '{{ tablet_targets }}'
        labels:
          component: vttablet
          app: vitess
          cluster: '{{ vitess_cluster }}'
          region: '{{ cell }}'
          keyspace: '{{ keyspace }}'
      mysqld:
      - targets: '{{ mysqld_targets }}'
        labels:
          component: mysqld
          app: vitess
          cluster: '{{ vitess_cluster }}'
          region: '{{ cell }}'
          keyspace: '{{ keyspace }}'
      gateways:
      - targets: '{{ gateway_targets }}'
        labels:
          component: vtgate
          app: vitess
          cluster: '{{ vitess_cluster }}'
          region: '{{ cell }}'
      vtctld:
      - targets: '{{ vtctld_targets }}'
        labels:
          component: vtctld
          app: vitess
          cluster: '{{ vitess_cluster }}'
          region: '{{ cell }}'
      nodes:
      - targets: '{{ node_targets }}'
        labels:
          component: node
          app: vitess
          cluster: '{{ vitess_cluster }}'
    prometheus_scrape_configs:
      - job_name: "node"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/nodes.yml"
      - job_name: "vitess-vttablet"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/tablets.yml"
      - job_name: "mysql"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/mysqld.yml"
      - job_name: "vitess-vtctld"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/vtctld.yml"
      - job_name: "vitess-vtgate"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/gateways.yml"
