---
- hosts: sysbench
  roles:
    - sysbench

- hosts: mysql
  roles:
    - vitess-build
  tasks:
    - name: Start mysql
      service:
        name: mysqld
        state: running
    - name: Create test Database
      mysql_db:
        name:
          - main
    - name: Create test user
      mysql_user:
        name: 'user'
        host_all: yes
        priv: '*.*:ALL'
