# Run the sysbench TPC-C benchmark and report the results
---
- hosts: sysbench
  vars:
    warehouses: 1000
    load_threads: 25
    threads: 150
    test_time: 300
  tasks:
    - name: Prepare sysbench
      when: provision is defined
      block:
        - name: Prepare sysbench
          shell: |
            sysbench --luajit-cmd=off --threads={{ load_threads }} --time={{ test_time }} --mysql-db=main --mysql-host=127.0.0.1 --mysql-port=3306 --db-ps-mode=disable --db-driver=mysql --report-interval=10 --mysql-ignore-errors=all --use_fk=0 --tables=1 --scale={{ warehouses }} ./tpcc.lua prepare
          args:
            chdir: /src/sysbench-tpcc/
          async: 86400
          poll: 0
          register: sysbench_prepare

        - async_status:
            jid: '{{ sysbench_prepare.ansible_job_id }}'
          register: job_result
          until: job_result.finished
          retries: 86400

    - name: ensure sysbench
      shell: |
        sysbench --luajit-cmd=off --threads={{ load_threads//7 }} --time={{ test_time }} --mysql-db=main --mysql-host=127.0.0.1 --mysql-port=3306 --db-ps-mode=disable --db-driver=mysql --report-interval=10 --mysql-ignore-errors=all --use_fk=0 --tables=1 --scale={{ warehouses }} ./tpcc.lua ensure
      args:
        chdir: /src/sysbench-tpcc/

    - name: Run sysbench
      block:
       - name: Run the test
         shell: |
           sysbench --luajit-cmd=off --threads={{ threads }} --time={{ test_time }} --mysql-db=main --mysql-host=127.0.0.1 --mysql-port=3306 --db-ps-mode=disable --db-driver=mysql --mysql-ignore-errors=all --use_fk=0 --rand-type=uniform --verbosity=0 --report_json=yes --tables=1 --scale={{ warehouses }} ./tpcc.lua run > /tmp/tpcc.json
         args:
           chdir: /src/sysbench-tpcc/
         async: '{{ test_time*2 }}'
         poll: 0
         register: sysbench_run
       - name: Wait for sysbench to finish
         async_status:
            jid: "{{ sysbench_run.ansible_job_id }}"
         register: job_result
         until: job_result.finished
         retries: '{{ test_time*2 }}'
       - debug:
           msg: '{{ job_result }}'
