---
- hosts: all
  roles:
    - vitess-build
- hosts: vtctld
  roles:
    - vtctld
- hosts: vtgate
  roles:
    - vtgate
- hosts: vttablet
  roles:
    - vttablet

- hosts: localhost
  connection: local
  tasks:
    - name: print
      debug:
        msg: Groups {{ groups['vtctld'][0] }}

    - name: Ensure Master
      shell: |
        set -o pipefail
        alias vc="vtctlclient -server {{ groups['vtctld'][0] }}:15999"
        for keyspace in $(vc GetKeyspaces); do
            echo "working on ${keyspace}"
            for shard in $(vc FindAllShardsInKeyspace ${keyspace} | jq -r 'keys[]'); do
                echo "working on ${shard}"
                master=$(vc ListShardTablets ${keyspace}/${shard} | grep master)
                if [ -z "${master}" ]; then
                  echo "setting master for ${keyspace}/${shard}"
                  vc InitShardMaster -force ${keyspace}/${shard} $(vc ListShardTablets ${keyspace}/${shard} | awk '{ print $1 }')
                fi
            done
        done
      args:
        executable: /bin/bash
      changed_when: false

    - name: Ensure OLTP VSchmea
      shell: |
        vtctlclient -server {{ groups['vtctld'][0] }}:15999 ApplyVSchema -vschema="$(cat ~/src/planetscale-benchmark/sysbench.json)" main
      when: tpcc is not defined

    - name: Ensure TPCC VSchmea
      shell: |
        vtctlclient -server {{ groups['vtctld'][0] }}:15999 ApplyVSchema -vschema="$(cat ~/src/planetscale-benchmark/tpcc_vschema.json)" main
      when: tpcc is defined
