---
etcd_platform: '{{ etcd_os }}-{{ etcd_arch }}'
etcd_name: etcd-{{ etcd_version }}-{{ etcd_platform }}
etcd_archive: '{{ etcd_name }}.{{ etcd_archive_suffix|default("tar.gz") }}'

etcd_archive_url: '{{ etcd_mirror }}/{{ etcd_version }}/{{ etcd_archive }}'
etcd_checksum: '{{ etcd_checksums[etcd_version][etcd_platform] }}'

etcd_scheme: "{% if etcd_secure %}https{% else %}http{% endif %}://"
etcd_cluster: "{% for host in groups[etcd_master_group_name] %}{{ hostvars[host]['ansible_fqdn'] }}={{ etcd_scheme }}{{ hostvars[host]['etcd_address_cluster'] }}:{{ etcd_port_peer }}{% if not loop.last %},{% endif %}{% endfor %}"
