- name: Stop service mysqlctld
  ansible.builtin.systemd:
    name: mysqlctld@*
    state: stopped

- name: Stop service vttablet
  ansible.builtin.systemd:
    name: vttablet@*
    state: stopped

- name: Stop service vtctld
  ansible.builtin.systemd:
    name: vtctld@*
    state: stopped

- name: Stop service cell
  ansible.builtin.systemd:
    name: cell@*
    state: stopped

- name: Stop service vtgate
  ansible.builtin.systemd:
    name: vtgate@*
    state: stopped

- name: Find Elements to remove
  find:
    path: /vt
    file_type: directory
  register: directories

- debug:
    msg: '{{directories}}'
    
- name: Remove Elements
  file:
    state: absent
    path: '{{item.path}}'
  loop: '{{ directories.files }}'
  when: clean is defined and ((directories.files | length) > 0)
