---
- name: "Get checksum for {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }} architecture"
  set_fact:
    __mysqld_exporter_checksum: "{{ item.split(' ')[0] }}"
  with_items:
    - "{{ lookup('url', 'https://github.com/prometheus/mysqld_exporter/releases/download/v' + mysqld_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
  when: "('linux-' + (go_arch_map[ansible_architecture] | default(ansible_architecture)) + '.tar.gz') in item"

- block:
    - name: Download mysqld_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
        dest: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
        checksum: "sha256:{{ __mysqld_exporter_checksum }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack mysqld_exporter binary
      become: false
      unarchive:
        src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/mysqld_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate mysqld_exporter binaries
      copy:
        src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/mysqld_exporter"
        dest: "/usr/local/bin/mysqld_exporter"
        mode: 0755
        owner: root
        group: root
      when: not ansible_check_mode
  when: mysqld_exporter_binary_local_dir | length == 0

- name: propagate locally distributed mysqld_exporter binary
  copy:
    src: "{{ mysqld_exporter_binary_local_dir }}/mysqld_exporter"
    dest: "/usr/local/bin/mysqld_exporter"
    mode: 0755
    owner: root
    group: root
  when: mysqld_exporter_binary_local_dir | length > 0
